import { createInterface } from "node:readline";
import type { Command } from "commander";
import { exitWith } from "../../lib/errors.js";
import { gh } from "../../lib/gh.js";
import type { PrListItem } from "./common.js";
import { listOpenPrs, resolveBaseBranch } from "./common.js";
import { createOneDraftPr, readPullRequestTemplate } from "./create.js";
import { buildBranchGraph } from "./graph.js";

const SYNC_BLOCK_START = "<!-- jj-scripts-sync -->";
const SYNC_BLOCK_END = "<!-- /jj-scripts-sync -->";

function* walkBranches(
  graph: Map<string, string[]>,
  root: string,
): Generator<[branch: string, target: string]> {
  const children = graph.get(root) ?? [];
  for (const branch of children) {
    yield [branch, root];
    yield* walkBranches(graph, branch);
  }
}

function confirm(question: string, defaultYes: boolean): Promise<boolean> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const prompt = defaultYes ? `${question} (Y/n): ` : `${question} (y/N): `;
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      rl.close();
      const normalized = answer.trim().toLowerCase();
      if (normalized === "") {
        resolve(defaultYes);
        return;
      }
      resolve(normalized === "y" || normalized === "yes");
    });
  });
}

function stripSyncBlock(body: string | null): string {
  if (!body || typeof body !== "string") {
    return "";
  }
  const startIdx = body.indexOf(SYNC_BLOCK_START);
  if (startIdx === -1) {
    return body.trimEnd();
  }
  const endIdx = body.indexOf(SYNC_BLOCK_END, startIdx);
  const endAfter = endIdx === -1 ? startIdx : endIdx + SYNC_BLOCK_END.length;
  const before = body.slice(0, startIdx).trimEnd();
  const after = body.slice(endAfter).replace(/^\n+/, "");
  return after ? `${before}\n\n${after}` : before;
}

function buildStackBlock(entries: { branch: string; url: string }[]): string {
  const lines = [
    SYNC_BLOCK_START,
    "",
    "> This pull request is part of a stack:",
    ...entries.map((e) => `> - [${e.branch}](${e.url})`),
    ">",
    "> <sup>Stack auto generated by jj-scripts</sup>",
    "",
    SYNC_BLOCK_END,
  ];
  return lines.join("\n");
}

async function getPrBody(prNumber: number, cwd: string): Promise<string> {
  const { stdout } = await gh(
    ["pr", "view", String(prNumber), "--json", "body"],
    { cwd },
  );
  const data = JSON.parse(stdout.trim()) as { body: string | null };
  return data.body ?? "";
}

async function updatePrBody(
  prNumber: number,
  body: string,
  cwd: string,
): Promise<void> {
  const { writeFile, mkdtemp, rm } = await import("node:fs/promises");
  const { tmpdir } = await import("node:os");
  const { join } = await import("node:path");
  const dir = await mkdtemp(join(tmpdir(), "jj-scripts-sync-"));
  const path = join(dir, "body.md");
  try {
    await writeFile(path, body, "utf8");
    await gh(["pr", "edit", String(prNumber), "--body-file", path], { cwd });
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

type SyncOptions = { yes?: boolean };

async function runSync(cwd: string, options: SyncOptions): Promise<void> {
  const root = await resolveBaseBranch(cwd);
  const graph = await buildBranchGraph(root, cwd);
  const pulls: PrListItem[] = await listOpenPrs(cwd);

  const prByHead = new Map<string, PrListItem>();
  for (const pr of pulls) {
    prByHead.set(pr.headRefName, pr);
  }

  /* oxlint-disable no-await-in-loop -- sequential: prompt and prByHead updates per branch */
  for (const [branch, target] of walkBranches(graph, root)) {
    const pr = prByHead.get(branch);
    if (pr) {
      if (pr.baseRefName !== target) {
        console.log(
          "[pr sync] Updating PR #%d base %s <- %s to %s <- %s",
          pr.number,
          pr.baseRefName,
          branch,
          target,
          branch,
        );
        await gh(["pr", "edit", String(pr.number), "--base", target], { cwd });
        pr.baseRefName = target;
      }
    } else {
      const shouldCreate =
        options.yes ||
        (await confirm(
          `PR from ${target} <- ${branch} doesn't exist. Create it?`,
          true,
        ));
      if (!shouldCreate) {
        console.log("[pr sync] Skipping create for %s <- %s", target, branch);
        continue;
      }
      const template = await readPullRequestTemplate(cwd);
      await createOneDraftPr(cwd, target, branch, template, {
        openInBrowser: false,
      });
      const { stdout } = await gh(
        [
          "pr",
          "view",
          branch,
          "--json",
          "number,headRefName,baseRefName,body,url",
        ],
        { cwd },
      );
      const newPr = JSON.parse(stdout.trim()) as PrListItem;
      pulls.push(newPr);
      prByHead.set(branch, newPr);
    }
  }
  /* oxlint-enable no-await-in-loop */

  const childrenOfRoot = graph.get(root) ?? [];
  const stackUpdatePromises = childrenOfRoot.map(async (stackRoot) => {
    const stackBranches: string[] = [stackRoot];
    const stack: string[] = [stackRoot];
    while (stack.length > 0) {
      const b = stack.pop()!;
      const children = graph.get(b) ?? [];
      for (const c of children) {
        stackBranches.push(c);
        stack.push(c);
      }
    }
    const entries: { branch: string; url: string }[] = [];
    for (const branch of stackBranches) {
      const pr = prByHead.get(branch);
      if (pr?.url) {
        entries.push({ branch, url: pr.url });
      }
    }
    if (entries.length === 0) {
      return;
    }
    const block = buildStackBlock(entries);
    const updates = await Promise.all(
      stackBranches
        .map((branch) => prByHead.get(branch))
        .filter((pr): pr is PrListItem => pr != null)
        .map(async (pr) => {
          const body = await getPrBody(pr.number, cwd);
          const withoutBlock = stripSyncBlock(body);
          const newBody = withoutBlock ? `${withoutBlock}\n\n${block}` : block;
          return { prNumber: pr.number, newBody };
        }),
    );
    await Promise.all(
      updates.map(({ prNumber, newBody }) =>
        updatePrBody(prNumber, newBody, cwd),
      ),
    );
  });
  await Promise.all(stackUpdatePromises);
}

export const registerSync = (pr: Command): void => {
  pr.command("sync")
    .description(
      "Sync PRs to branch stack: find/create PRs, update base, update stack comments",
    )
    .option("-y, --yes", "Create missing PRs without prompting")
    .action(async (opts: SyncOptions) => {
      if (!process.stdin.isTTY && !opts.yes) {
        exitWith(
          1,
          "pr sync requires a TTY to prompt, or pass --yes to create missing PRs without prompting.",
        );
      }
      await runSync(process.cwd(), opts);
    });
};
